version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=sobrevidas_db
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/sobrevidas_db",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
       }'

volumes:
  db: